### ISSUE TITLE
Bug: It won't install with npm

### ISSUE THREAD

**Issue by remy90** [formidable-webview/ersatz#1]
`$ npm i --save-dev @formidable-webview/ersatz @formidable-webview/ersatz-testing`
```
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! prepareGitDep npm ERR! Unsupported URL Type "link:": link:./scripts/eslint-plugin
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     .npm/_logs/2020-10-24T10_20_03_565Z-debug.log
npm ERR! prepareGitDep
npm ERR! premature close

npm ERR! A complete log of this run can be found in:
npm ERR!     .npm/_logs/2020-10-24T10_20_04_173Z-debug.log
```

On the one occasion it added to my package.json, it didn't manage to add a directory to node_modules (and `npm install` erred with the same issue above. Only discarding the changes resolved the issue.

**Comment by jsamr** [comment]
@remy90 Thanks, I'll take a look

**Comment by jsamr** [comment]
@remy90 I did a little `grep -R "link:./scripts/eslint-plugin"` in the master branch and had the following matches:
```
node_modules/jest-environment-jsdom/node_modules/jsdom/package.json:    "eslint-plugin-jsdom-internal": "link:./scripts/eslint-plugin",
node_modules/jsdom/package.json:    "eslint-plugin-jsdom-internal": "link:./scripts/eslint-plugin",
```
I'll check and see if those upstream packages have published a fix and let you know.

**Comment by jsamr** [comment]
I am still able to reproduce this... I'll fill a bug in npm issue tracker.
I noticed however, that if you use `--only=dev`, the package will be installed despite the error.

```
npm i --only=dev @formidable-webview/ersatz @formidable-webview/ersatz-testing
```

**Comment by remy90** [comment]
Thanks for the above, the following did the trick for a dev dependency: 
```npm i --only=dev @formidable-webview/ersatz @formidable-webview/ersatz-testing -D ```
