### ISSUE TITLE
Documented example test fails

### ISSUE THREAD

**Issue by remy90** [formidable-webview/ersatz#2]
I've tested the documented example from [here](https://github.com/formidable-webview/ersatz/tree/master/packages/ersatz-testing#usage-with-jest-mocks) and get a failing test. I should add, I've created a new file and am testing this in isolation, copied & pasted. Stepping through the issue, `_skeletton.webViewLifecycle` is undefined. I couldn't find anything in JSDOMEngine.js or Skeletton.tsx that would set it. The error message is as follows:

> MyComponent
>     ✕ should make awesomeGlobal available to window with value “1” (375 ms)
> 
>   ● MyComponent › should make awesomeGlobal available to window with value “1”
> 
>     TypeError: Cannot read property 'handleLoadStart' of undefined
> 
>       at initDOM (node_modules/@formidable-webview/ersatz/lib/commonjs/JSDOMEngine.tsx:77:20)
>       at node_modules/@formidable-webview/ersatz/lib/commonjs/JSDOMEngine.tsx:120:12
>       at mountMemo (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6191:19)
>       at Object.useMemo (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6487:16)
>       at useMemo (node_modules/react/cjs/react.development.js:1521:21)
>       at DOMEngine (node_modules/@formidable-webview/ersatz/lib/commonjs/JSDOMEngine.tsx:119:15)
>       at renderWithHooks (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5552:18)
>       at updateForwardRef (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7288:20)
>       at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9068:16)
>       at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12649:12)
> 
>   console.error
>     The above error occurred in the <ForwardRef(DOMEngine)> component:
>         in ForwardRef(DOMEngine) (created by SourceLoader)
>         in View (created by View)
>         in View (created by SourceLoader)
>         in SourceLoader (created by ForwardRef)
>         in ForwardRef (created by Skeletton)
>         in View (created by View)
>         in View (created by ScrollView)
>         in RCTScrollView (created by RCTScrollView)
>         in RCTScrollView (created by ScrollView)
>         in ScrollView (created by Skeletton)
>         in Skeletton (created by ForwardRef(Ersatz))
>         in ForwardRef(Ersatz) (created by MyComponent)
>         in MyComponent
>     
>     Consider adding an error boundary to your tree to customize error handling behavior.
> 
>       at logCapturedError (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10141:21)
>       at logError (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10178:5)
>       at update.callback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11288:5)
>       at callCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3259:12)
>       at commitUpdateQueue (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3280:9)
>       at commitLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10497:11)
>       at commitLayoutEffects (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13295:7)
> 
>   console.error
>     Error: Uncaught [TypeError: Cannot read property '_ownerDocument' of undefined]
>         at reportException (node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:62:24)
>         at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:333:9)
>         at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
>         at DocumentImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
>         at fireAnEvent (node_modules/jsdom/lib/jsdom/living/helpers/events.js:18:36)
>         at dispatchEvent (node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:475:9)
>         at node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:480:11
>         at tryCallTwo (node_modules/promise/lib/core.js:45:5)
>         at doResolve (node_modules/promise/lib/core.js:200:13)
>         at new Promise (node_modules/promise/lib/core.js:66:3) TypeError: Cannot read property '_ownerDocument' of undefined
>         at innerInvokeEventListeners (/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:327:26)
>         at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
>         at EventTargetImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
>         at fireAnEvent (node_modules/jsdom/lib/jsdom/living/helpers/events.js:18:36)
>         at Document.<anonymous> (node_modules/jsdom/lib/jsdom/browser/Window.js:776:9)
>         at Document.callTheUserObjectsOperation (node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
>         at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:318:25)
>         at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
>         at DocumentImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
>         at fireAnEvent (node_modules/jsdom/lib/jsdom/living/helpers/events.js:18:36)
> 
>       at VirtualConsole.<anonymous> (node_modules/jsdom/lib/jsdom/virtual-console.js:29:45)
>       at reportException (node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:28)
>       at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:333:9)
>       at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
>       at DocumentImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
>       at fireAnEvent (node_modules/jsdom/lib/jsdom/living/helpers/events.js:18:36)
> 
> Test Suites: 1 failed, 1 total
> Tests:       1 failed, 1 total
> Time:        3.001 s, estimated 4 s
> Ran all test suites matching /MyComponent.test.tsx/i.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! DoctorlinkApp@2.0.4 test: `jest "MyComponent.test.tsx"`
> npm ERR! Exit status 1

I would however, like to point out that the following snapshot test is sucessful, where WebView is a child component of Home:
```
  it.only(`should match snapshot`, () => {
    const component = render(<Home navigation={navigationMock} />);
    expect(component).toMatchSnapshot();
  });
```

**Comment by jsamr** [comment]
> _skeletton.webViewLifecycle is undefined

It could be that npm failed to resolve `ersatz` dependencies because of #1...
Check your package-lock.json and assert that there is a resolved dependency for `@formidable-webview/skeletton`.

If there isn't, could you uninstall / reinstall ersatz and make sure you installed version 2.0.2?

**Comment by jsamr** [comment]
@remy90 OK; the problem is due to packaging. The bundled files don't seem to be pre-built. I am investigating.

**Comment by remy90** [comment]
It did cross my mind that #1 might be related.
Looks like the latest Skeletton release is 1.0.1, which is what I have installed:
```
    "@formidable-webview/ersatz": {
      "version": "2.0.2",
      "resolved": "https://registry.npmjs.org/@formidable-webview/ersatz/-/ersatz-2.0.2.tgz",
      "dev": true,
      "requires": {
        "@formidable-webview/ersatz-core": "2.0.2",
        "@formidable-webview/skeletton": "1.0.1",
        "assert": "^2.0.0",
        "canvas": "^2.6.1",
        "jsdom": "^16.4.0",
        "node-fetch": "^3.0.0-beta.9"
      },
      "dependencies": {
        "data-uri-to-buffer": {
          "version": "3.0.1",
          "resolved": "https://registry.npmjs.org/data-uri-to-buffer/-/data-uri-to-buffer-3.0.1.tgz",
          "dev": true
        },
        "node-fetch": {
          "version": "3.0.0-beta.9",
          "resolved": "https://registry.npmjs.org/node-fetch/-/node-fetch-3.0.0-beta.9.tgz",
          "dev": true,
          "requires": {
            "data-uri-to-buffer": "^3.0.1",
            "fetch-blob": "^2.1.1"
          }
        }
      }
    }
```

**Comment by jsamr** [comment]
@remy90 The issue stems from the fact [Yarn 2 only supports a subset of npm lifecycle hooks](https://yarnpkg.com/advanced/lifecycle-scripts/) ... and I was using `prepare`, which is not supported! I am going to publish a fix ASAP.

**Comment by jsamr** [comment]
@remy90 Should be fixed with ersatz@2.0.3, waiting for your confirmation!

**Comment by remy90** [comment]
Just updated, the test passes, many thanks!!

**Comment by jsamr** [comment]
@remy90 I should be the one thanking you for catching those issues :-)
