### ISSUE TITLE
"Project Homepage"-link from npmjs leads to a 404

### ISSUE THREAD

**Issue by flq** [formidable-webview/ersatz#3]
Hello,
that link points to https://github.com/formidable-webview/tree/master/packages/ersatz-testing#readme

but it seems that it should point to https://github.com/formidable-webview/ubiquitous/tree/master/packages/ersatz#readme

Cheers

**Comment by jsamr** [comment]
@flq Thank you for reporting this issue! Should be fixed now.

**Comment by flq** [comment]
Superfast, cheers! 👍🏼
